name: consumer
description: GRRADO Customer Web Portal
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  core:
    path: ../../shared/core
  domain:
    path: ../../shared/domain
  data:
    path: ../../shared/data
  ui:
    path: ../../shared/ui
  auth:
    path: ../../shared/auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
